In [1]:
import pandas as pd
import os

# Function to find the row with the best combination of RMSE and R^2 values for each model
def find_best_row(file_paths, number_of_features):
    best_rows = {}

    for file_path in file_paths:
        excel_data = pd.ExcelFile(file_path)
        file_name = os.path.basename(file_path)

        for sheet_name in excel_data.sheet_names:
            if sheet_name in ["MLR", "DT", "RF", "KNN", "SVM"]:
                df = pd.read_excel(excel_data, sheet_name=sheet_name)

                # Filter rows based on the condition: "Number of features" < number_of_features
                df_filtered = df[df['Number of features'] < number_of_features]

                # Find the best row index after filtering
                best_row_index = (
                    df_filtered['Test RMSE'].idxmin(),
                    df_filtered['Test data R^2 score'].idxmax()
                )

                best_rmse = df.loc[best_row_index[0], 'Test RMSE']
                best_r2 = df.loc[best_row_index[1], 'Test data R^2 score']

                if sheet_name not in best_rows:
                    best_rows[sheet_name] = {
                        'File': file_name,
                        'Best Row Index': best_row_index,
                        'Best RMSE': best_rmse,
                        'Best R^2': best_r2
                    }
                else:
                    curr_rmse = best_rows[sheet_name]['Best RMSE']
                    curr_r2 = best_rows[sheet_name]['Best R^2']

                    if best_rmse < curr_rmse and best_r2 > curr_r2:
                        best_rows[sheet_name] = {
                            'File': file_name,
                            'Best Row Index': best_row_index,
                            'Best RMSE': best_rmse,
                            'Best R^2': best_r2
                        }

    return best_rows

In [2]:
file_paths = ['../Data/Quality_ee_15_.xlsx', 
              '../Data/Quality_ee_28_.xlsx', 
              '../Data/Quality_ee_42_.xlsx']

best_rows = find_best_row(file_paths, 10)
# Displaying the best rows for each model across files
for model, row_info in best_rows.items():
    file_name = row_info['File']
    row_index = row_info['Best Row Index']
    print(f"Model: {model}")
    print(f"File: {file_name}")
    print("Best Row:")
    print(pd.read_excel('../Data/'+file_name, sheet_name=model).iloc[row_index[0]])
    print()

Model: MLR
File: Quality_ee_15_.xlsx
Best Row:
Unnamed: 0                  2.000000
Correlation threshold       0.450000
Training data R^2 score     0.704633
Test data R^2 score         0.023657
Training RMSE              12.720963
Test RMSE                  16.365558
Number of features          8.000000
Name: 2, dtype: float64

Model: DT
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 197.000000
Correlation threshold        0.500000
Training data R^2 score      0.578002
Test data R^2 score          0.109453
Training RMSE               15.328648
Test RMSE                   12.621766
Number of features           2.000000
Depth number                 3.000000
Name: 197, dtype: float64

Model: RF
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 97.000000
Correlation threshold       0.480000
Training data R^2 score     0.816623
Test data R^2 score         0.642275
Training RMSE              10.104628
Test RMSE                   7.999566
Number of features          5.000000
Number of estimators        4.000000
Name: 97, dtype: float64

Model: KNN
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  6.000000
Correlation threshold       0.490000
Training data R^2 score     0.493433
Test data R^2 score         0.350385
Training RMSE              16.794493
Test RMSE                  10.780023
Number of features          4.000000
Name: 6, dtype: float64

Model: SVM
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  6.000000
Correlation threshold       0.490000
Training data R^2 score     0.089497
Test data R^2 score         0.260044
Training RMSE              22.515886
Test RMSE                  11.505212
Number of features          4.000000
Name: 6, dtype: float64

In [3]:
file_paths = ['../Data/Quality_ee_15_.xlsx', 
              '../Data/Quality_ee_28_.xlsx', 
              '../Data/Quality_ee_42_.xlsx']

best_rows = find_best_row(file_paths, 6)
# Displaying the best rows for each model across files
for model, row_info in best_rows.items():
    file_name = row_info['File']
    row_index = row_info['Best Row Index']
    print(f"Model: {model}")
    print(f"File: {file_name}")
    print("Best Row:")
    print(pd.read_excel('../Data/'+file_name, sheet_name=model).iloc[row_index[0]])
    print()

Model: MLR
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  7.000000
Correlation threshold       0.500000
Training data R^2 score     0.283621
Test data R^2 score        -0.160872
Training RMSE              19.971920
Test RMSE                  14.410657
Number of features          2.000000
Name: 7, dtype: float64

Model: DT
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 197.000000
Correlation threshold        0.500000
Training data R^2 score      0.578002
Test data R^2 score          0.109453
Training RMSE               15.328648
Test RMSE                   12.621766
Number of features           2.000000
Depth number                 3.000000
Name: 197, dtype: float64

Model: RF
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 97.000000
Correlation threshold       0.480000
Training data R^2 score     0.816623
Test data R^2 score         0.642275
Training RMSE              10.104628
Test RMSE                   7.999566
Number of features          5.000000
Number of estimators        4.000000
Name: 97, dtype: float64

Model: KNN
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  6.000000
Correlation threshold       0.490000
Training data R^2 score     0.493433
Test data R^2 score         0.350385
Training RMSE              16.794493
Test RMSE                  10.780023
Number of features          4.000000
Name: 6, dtype: float64

Model: SVM
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  6.000000
Correlation threshold       0.490000
Training data R^2 score     0.089497
Test data R^2 score         0.260044
Training RMSE              22.515886
Test RMSE                  11.505212
Number of features          4.000000
Name: 6, dtype: float64

In [4]:
file_paths = ['../Data/Quality_ee_15_.xlsx', 
              '../Data/Quality_ee_28_.xlsx', 
              '../Data/Quality_ee_42_.xlsx']

best_rows = find_best_row(file_paths, 5)
# Displaying the best rows for each model across files
for model, row_info in best_rows.items():
    file_name = row_info['File']
    row_index = row_info['Best Row Index']
    print(f"Model: {model}")
    print(f"File: {file_name}")
    print("Best Row:")
    print(pd.read_excel('../Data/'+file_name, sheet_name=model).iloc[row_index[0]])
    print()

Model: MLR
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  7.000000
Correlation threshold       0.500000
Training data R^2 score     0.283621
Test data R^2 score        -0.160872
Training RMSE              19.971920
Test RMSE                  14.410657
Number of features          2.000000
Name: 7, dtype: float64

Model: DT
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 197.000000
Correlation threshold        0.500000
Training data R^2 score      0.578002
Test data R^2 score          0.109453
Training RMSE               15.328648
Test RMSE                   12.621766
Number of features           2.000000
Depth number                 3.000000
Name: 197, dtype: float64

Model: RF
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 116.000000
Correlation threshold        0.490000
Training data R^2 score      0.796790
Test data R^2 score          0.370691
Training RMSE               10.637034
Test RMSE                   10.610202
Number of features           4.000000
Number of estimators         4.000000
Name: 116, dtype: float64

Model: KNN
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  6.000000
Correlation threshold       0.490000
Training data R^2 score     0.493433
Test data R^2 score         0.350385
Training RMSE              16.794493
Test RMSE                  10.780023
Number of features          4.000000
Name: 6, dtype: float64

Model: SVM
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  6.000000
Correlation threshold       0.490000
Training data R^2 score     0.089497
Test data R^2 score         0.260044
Training RMSE              22.515886
Test RMSE                  11.505212
Number of features          4.000000
Name: 6, dtype: float64

In [5]:
file_paths = ['../Data/Quality_ee_15_.xlsx', 
              '../Data/Quality_ee_28_.xlsx', 
              '../Data/Quality_ee_42_.xlsx']

best_rows = find_best_row(file_paths, 4)
# Displaying the best rows for each model across files
for model, row_info in best_rows.items():
    file_name = row_info['File']
    row_index = row_info['Best Row Index']
    print(f"Model: {model}")
    print(f"File: {file_name}")
    print("Best Row:")
    print(pd.read_excel('../Data/'+file_name, sheet_name=model).iloc[row_index[0]])
    print()

Model: MLR
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  7.000000
Correlation threshold       0.500000
Training data R^2 score     0.283621
Test data R^2 score        -0.160872
Training RMSE              19.971920
Test RMSE                  14.410657
Number of features          2.000000
Name: 7, dtype: float64

Model: DT
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 197.000000
Correlation threshold        0.500000
Training data R^2 score      0.578002
Test data R^2 score          0.109453
Training RMSE               15.328648
Test RMSE                   12.621766
Number of features           2.000000
Depth number                 3.000000
Name: 197, dtype: float64

Model: RF
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 140.000000
Correlation threshold        0.500000
Training data R^2 score      0.814696
Test data R^2 score          0.099741
Training RMSE               10.157590
Test RMSE                   12.690406
Number of features           2.000000
Number of estimators         9.000000
Name: 140, dtype: float64

Model: KNN
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  7.000000
Correlation threshold       0.500000
Training data R^2 score     0.357028
Test data R^2 score         0.001665
Training RMSE              18.921020
Test RMSE                  13.363799
Number of features          2.000000
Name: 7, dtype: float64

Model: SVM
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  7.000000
Correlation threshold       0.500000
Training data R^2 score    -0.181155
Test data R^2 score         0.181102
Training RMSE              25.644948
Test RMSE                  12.103377
Number of features          2.000000
Name: 7, dtype: float64

In [6]:
file_paths = ['../Data/Quality_ee_15_.xlsx', 
              '../Data/Quality_ee_28_.xlsx', 
              '../Data/Quality_ee_42_.xlsx']

best_rows = find_best_row(file_paths, 3)
# Displaying the best rows for each model across files
for model, row_info in best_rows.items():
    file_name = row_info['File']
    row_index = row_info['Best Row Index']
    print(f"Model: {model}")
    print(f"File: {file_name}")
    print("Best Row:")
    print(pd.read_excel('../Data/'+file_name, sheet_name=model).iloc[row_index[0]])
    print()

Model: MLR
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  7.000000
Correlation threshold       0.500000
Training data R^2 score     0.283621
Test data R^2 score        -0.160872
Training RMSE              19.971920
Test RMSE                  14.410657
Number of features          2.000000
Name: 7, dtype: float64

Model: DT
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 197.000000
Correlation threshold        0.500000
Training data R^2 score      0.578002
Test data R^2 score          0.109453
Training RMSE               15.328648
Test RMSE                   12.621766
Number of features           2.000000
Depth number                 3.000000
Name: 197, dtype: float64

Model: RF
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 140.000000
Correlation threshold        0.500000
Training data R^2 score      0.814696
Test data R^2 score          0.099741
Training RMSE               10.157590
Test RMSE                   12.690406
Number of features           2.000000
Number of estimators         9.000000
Name: 140, dtype: float64

Model: KNN
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  7.000000
Correlation threshold       0.500000
Training data R^2 score     0.357028
Test data R^2 score         0.001665
Training RMSE              18.921020
Test RMSE                  13.363799
Number of features          2.000000
Name: 7, dtype: float64

Model: SVM
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  7.000000
Correlation threshold       0.500000
Training data R^2 score    -0.181155
Test data R^2 score         0.181102
Training RMSE              25.644948
Test RMSE                  12.103377
Number of features          2.000000
Name: 7, dtype: float64

In [7]:
import pandas as pd
import os

# Function to find the row with the best combination of RMSE and R^2 values for each model
def find_best_row(file_paths, number_of_features):
    best_rows = {}

    for file_path in file_paths:
        excel_data = pd.ExcelFile(file_path)
        file_name = os.path.basename(file_path)

        for sheet_name in excel_data.sheet_names:
            if sheet_name in ["MLR", "DT", "RF", "KNN", "SVM"]:
                df = pd.read_excel(excel_data, sheet_name=sheet_name)

                # Filter rows based on the condition: "Number of features" < number_of_features
                df_filtered = df[df['Number of features'] < number_of_features]

                # Find the best row index after filtering
                best_rmse_index = df_filtered['Test RMSE'].idxmin()
                best_r2_index = df_filtered['Test data R^2 score'].idxmax()

                best_rmse = df.loc[best_rmse_index, 'Test RMSE']
                best_r2 = df.loc[best_r2_index, 'Test data R^2 score']
                best_train_r2 = df.loc[best_r2_index, 'Training data R^2 score']

                # Ensure that the Training data R^2 score is greater than Test data R^2 score
                if best_train_r2 > best_r2:
                    if sheet_name not in best_rows:
                        best_rows[sheet_name] = {
                            'File': file_name,
                            'Best Row Index': best_r2_index,
                            'Best RMSE': best_rmse,
                            'Best R^2': best_r2
                        }
                    else:
                        curr_rmse = best_rows[sheet_name]['Best RMSE']
                        curr_r2 = best_rows[sheet_name]['Best R^2']

                        if best_rmse < curr_rmse and best_r2 > curr_r2:
                            best_rows[sheet_name] = {
                                'File': file_name,
                                'Best Row Index': best_r2_index,
                                'Best RMSE': best_rmse,
                                'Best R^2': best_r2
                            }

    return best_rows

In [8]:
# ee best

In [9]:
file_paths = ['../Data/Quality_ee_15_.xlsx', 
              '../Data/Quality_ee_28_.xlsx', 
              '../Data/Quality_ee_42_.xlsx']

best_rows = find_best_row(file_paths, 10)
# Displaying the best rows for each model across files
for model, row_info in best_rows.items():
    file_name = row_info['File']
    row_index = row_info['Best Row Index']
    print(f"Model: {model}")
    print(f"File: {file_name}")
    print("Best Row:")
    print(pd.read_excel('../Data/'+file_name, sheet_name=model).iloc[row_index])
    print()

Model: MLR
File: Quality_ee_15_.xlsx
Best Row:
Unnamed: 0                  2.000000
Correlation threshold       0.450000
Training data R^2 score     0.704633
Test data R^2 score         0.023657
Training RMSE              12.720963
Test RMSE                  16.365558
Number of features          8.000000
Name: 2, dtype: float64

Model: DT
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 197.000000
Correlation threshold        0.500000
Training data R^2 score      0.578002
Test data R^2 score          0.109453
Training RMSE               15.328648
Test RMSE                   12.621766
Number of features           2.000000
Depth number                 3.000000
Name: 197, dtype: float64

Model: RF
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 97.000000
Correlation threshold       0.480000
Training data R^2 score     0.816623
Test data R^2 score         0.642275
Training RMSE              10.104628
Test RMSE                   7.999566
Number of features          5.000000
Number of estimators        4.000000
Name: 97, dtype: float64

Model: KNN
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  6.000000
Correlation threshold       0.490000
Training data R^2 score     0.493433
Test data R^2 score         0.350385
Training RMSE              16.794493
Test RMSE                  10.780023
Number of features          4.000000
Name: 6, dtype: float64

Model: SVM
File: Quality_ee_15_.xlsx
Best Row:
Unnamed: 0                  5.000000
Correlation threshold       0.480000
Training data R^2 score     0.439692
Test data R^2 score         0.172514
Training RMSE              17.520747
Test RMSE                  15.066414
Number of features          5.000000
Name: 5, dtype: float64

In [10]:
file_paths = ['../Data/Quality_ee_15_.xlsx', 
              '../Data/Quality_ee_28_.xlsx', 
              '../Data/Quality_ee_42_.xlsx']

best_rows = find_best_row(file_paths, 5)
# Displaying the best rows for each model across files
for model, row_info in best_rows.items():
    file_name = row_info['File']
    row_index = row_info['Best Row Index']
    print(f"Model: {model}")
    print(f"File: {file_name}")
    print("Best Row:")
    print(pd.read_excel('../Data/'+file_name, sheet_name=model).iloc[row_index])
    print()

Model: MLR
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  7.000000
Correlation threshold       0.500000
Training data R^2 score     0.283621
Test data R^2 score        -0.160872
Training RMSE              19.971920
Test RMSE                  14.410657
Number of features          2.000000
Name: 7, dtype: float64

Model: DT
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 197.000000
Correlation threshold        0.500000
Training data R^2 score      0.578002
Test data R^2 score          0.109453
Training RMSE               15.328648
Test RMSE                   12.621766
Number of features           2.000000
Depth number                 3.000000
Name: 197, dtype: float64

Model: RF
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                 116.000000
Correlation threshold        0.490000
Training data R^2 score      0.796790
Test data R^2 score          0.370691
Training RMSE               10.637034
Test RMSE                   10.610202
Number of features           4.000000
Number of estimators         4.000000
Name: 116, dtype: float64

Model: KNN
File: Quality_ee_28_.xlsx
Best Row:
Unnamed: 0                  6.000000
Correlation threshold       0.490000
Training data R^2 score     0.493433
Test data R^2 score         0.350385
Training RMSE              16.794493
Test RMSE                  10.780023
Number of features          4.000000
Name: 6, dtype: float64

Model: SVM
File: Quality_ee_15_.xlsx
Best Row:
Unnamed: 0                  7.000000
Correlation threshold       0.500000
Training data R^2 score    -0.120930
Test data R^2 score        -0.238055
Training RMSE              24.781550
Test RMSE                  18.428904
Number of features          2.000000
Name: 7, dtype: float64

In [1]:
import pandas as pd

# Define the path to the Excel file
file_path = '../Data/Quality_ee_15_.xlsx'

# Define the sheets and metrics
sheets = ["MLR", "DT", "RF", "KNN", "SVM"]
metrics = ['Training data R^2 score', 'Test data R^2 score', 'Training RMSE', 'Test RMSE']
number_of_features = 10

# Initialize a dictionary to store the best models
best_models = {}

# Iterate through each sheet to find the best model
for sheet in sheets:
    # Read the data from the current sheet
    df = pd.read_excel(file_path, sheet_name=sheet)
    df_filtered = df[df['Number of features'] < number_of_features]
    
    # Filter the DataFrame based on the criteria
    filtered_df = df_filtered[df_filtered['Test data R^2 score'] > 0.36]
    
    if not filtered_df.empty:
        # Find the row with the maximum Test data R^2 score
        best_model = filtered_df.loc[filtered_df['Test data R^2 score'].idxmax()]
        best_models[sheet] = best_model
    else:
        print(f"No models in sheet {sheet} meet the criteria (Test data R^2 score > 0.x).")

# Convert the results to a DataFrame for better visualization
best_models_df = pd.DataFrame.from_dict(best_models, orient='index')

# Print the best models for each method
print("Best Models for Each Method:")
best_models_df

No models in sheet MLR meet the criteria (Test data R^2 score > 0.x).
No models in sheet DT meet the criteria (Test data R^2 score > 0.x).
No models in sheet KNN meet the criteria (Test data R^2 score > 0.x).
No models in sheet SVM meet the criteria (Test data R^2 score > 0.x).
Best Models for Each Method:

,Unnamed: 0,Correlation threshold,Training data R^2 score,Test data R^2 score,Training RMSE,Test RMSE,Number of features,Number of estimators
RF,52.0,0.45,0.950764,0.501656,5.193767,11.692141,8.0,16.0

In [2]:
import pandas as pd

# Define the path to the Excel file
file_path = '../Data/Quality_ee_28_.xlsx'

# Define the sheets and metrics
sheets = ["MLR", "DT", "RF", "KNN", "SVM"]
metrics = ['Training data R^2 score', 'Test data R^2 score', 'Training RMSE', 'Test RMSE']
number_of_features = 10

# Initialize a dictionary to store the best models
best_models = {}

# Iterate through each sheet to find the best model
for sheet in sheets:
    # Read the data from the current sheet
    df = pd.read_excel(file_path, sheet_name=sheet)
    df_filtered = df[df['Number of features'] < number_of_features]
    
    # Filter the DataFrame based on the criteria
    filtered_df = df_filtered[df_filtered['Test data R^2 score'] > 0.36]
    
    if not filtered_df.empty:
        # Find the row with the maximum Test data R^2 score
        best_model = filtered_df.loc[filtered_df['Test data R^2 score'].idxmax()]
        best_models[sheet] = best_model
    else:
        print(f"No models in sheet {sheet} meet the criteria (Test data R^2 score > 0.x).")

# Convert the results to a DataFrame for better visualization
best_models_df = pd.DataFrame.from_dict(best_models, orient='index')

# Print the best models for each method
print("Best Models for Each Method:")
best_models_df

No models in sheet MLR meet the criteria (Test data R^2 score > 0.x).
No models in sheet DT meet the criteria (Test data R^2 score > 0.x).
No models in sheet KNN meet the criteria (Test data R^2 score > 0.x).
No models in sheet SVM meet the criteria (Test data R^2 score > 0.x).
Best Models for Each Method:

,Unnamed: 0,Correlation threshold,Training data R^2 score,Test data R^2 score,Training RMSE,Test RMSE,Number of features,Number of estimators
RF,97.0,0.48,0.816623,0.642275,10.104628,7.999566,5.0,4.0

In [3]:
import pandas as pd

# Define the path to the Excel file
file_path = '../Data/Quality_ee_42_.xlsx'

# Define the sheets and metrics
sheets = ["MLR", "DT", "RF", "KNN", "SVM"]
metrics = ['Training data R^2 score', 'Test data R^2 score', 'Training RMSE', 'Test RMSE']
number_of_features = 10

# Initialize a dictionary to store the best models
best_models = {}

# Iterate through each sheet to find the best model
for sheet in sheets:
    # Read the data from the current sheet
    df = pd.read_excel(file_path, sheet_name=sheet)
    df_filtered = df[df['Number of features'] < number_of_features]
    
    # Filter the DataFrame based on the criteria
    filtered_df = df_filtered[df_filtered['Test data R^2 score'] > 0.36]
    
    if not filtered_df.empty:
        # Find the row with the maximum Test data R^2 score
        best_model = filtered_df.loc[filtered_df['Test data R^2 score'].idxmax()]
        best_models[sheet] = best_model
    else:
        print(f"No models in sheet {sheet} meet the criteria (Test data R^2 score > 0.x).")

# Convert the results to a DataFrame for better visualization
best_models_df = pd.DataFrame.from_dict(best_models, orient='index')

# Print the best models for each method
print("Best Models for Each Method:")
best_models_df

No models in sheet SVM meet the criteria (Test data R^2 score > 0.x).
Best Models for Each Method:

,Unnamed: 0,Correlation threshold,Training data R^2 score,Test data R^2 score,Training RMSE,Test RMSE,Number of features,Depth number,Number of estimators
MLR,2.0,0.45,0.537072,0.663814,12.597520,18.134635,8.0,NaN,NaN
DT,173.0,0.49,0.993619,0.602715,1.479020,19.713770,4.0,7.0,NaN
RF,41.0,0.45,0.828977,0.646847,7.656941,18.586614,8.0,NaN,5.0
KNN,6.0,0.49,0.360062,0.365684,14.811440,24.909882,4.0,NaN,NaN