In [1]:
import pandas as pd

# Define the path to the Excel file
file_path = '../Data/Quality_ee_15_.xlsx'

# Define the sheets and metrics
sheets = ["MLR", "DT", "RF", "KNN", "SVM"]
metrics = ['Training data R^2 score', 'Test data R^2 score', 'Training RMSE', 'Test RMSE']
number_of_features = 10
# Initialize a dictionary to store the best models
best_models = {}

# Iterate through each sheet to find the best model
for sheet in sheets:
    # Read the data from the current sheet
    df = pd.read_excel(file_path, sheet_name=sheet)
    df_filtered = df[df['Number of features'] < number_of_features]
    # Filter the DataFrame based on the criteria
    # The model must have higher training parameters than test parameters
    filtered_df = df_filtered[(df_filtered['Training data R^2 score'] > df_filtered['Test data R^2 score']) & 
                     (df_filtered['Training RMSE'] < df_filtered['Test RMSE']) & 
                              (df_filtered['Test data R^2 score'] > 0.36)]
    
    if not filtered_df.empty:
        # Find the row with the maximum Test Accuracy
        best_model = filtered_df.loc[filtered_df['Test data R^2 score'].idxmax()]
        best_model = filtered_df.loc[filtered_df['Correlation threshold'].idxmax()]
        best_models[sheet] = best_model

# Convert the results to a DataFrame for better visualization
best_models_df = pd.DataFrame.from_dict(best_models, orient='index')

# Print the best models for each method
print("Best Models for Each Method:")
best_models_df

Best Models for Each Method:

Empty DataFrame
Columns: []
Index: []

In [2]:
#best_models_df['Test data R^2 score']['DT']

In [2]:
try:
    import numpy as np
    print("The correlation coefficient for test data equals: "+str(np.sqrt(best_models_df['Test data R^2 score']['DT'])))
    print("The correlation coefficient for training data equals: "+str(np.sqrt(best_models_df['Training data R^2 score']['DT'])))
except:
    print("Error gathering the data...")

Error gathering the data...

In [3]:
import pandas as pd

# Define the path to the Excel file
file_path = '../Data/Quality_ee_28_.xlsx'

# Define the sheets and metrics
sheets = ["MLR", "DT", "RF", "KNN", "SVM"]
metrics = ['Training data R^2 score', 'Test data R^2 score', 'Training RMSE', 'Test RMSE']
number_of_features = 10
# Initialize a dictionary to store the best models
best_models = {}

# Iterate through each sheet to find the best model
for sheet in sheets:
    # Read the data from the current sheet
    df = pd.read_excel(file_path, sheet_name=sheet)
    df_filtered = df[df['Number of features'] < number_of_features]
    # Filter the DataFrame based on the criteria
    # The model must have higher training parameters than test parameters
    filtered_df = df_filtered[(df_filtered['Training data R^2 score'] > df_filtered['Test data R^2 score']) & 
                     (df_filtered['Training RMSE'] < df_filtered['Test RMSE']) & 
                              (df_filtered['Test data R^2 score'] > 0.36)]
    
    if not filtered_df.empty:
        # Find the row with the maximum Test Accuracy
        best_model = filtered_df.loc[filtered_df['Test data R^2 score'].idxmax()]
        best_model = filtered_df.loc[filtered_df['Correlation threshold'].idxmax()]
        best_models[sheet] = best_model

# Convert the results to a DataFrame for better visualization
best_models_df = pd.DataFrame.from_dict(best_models, orient='index')

# Print the best models for each method
print("Best Models for Each Method:")
best_models_df

Best Models for Each Method:

,Unnamed: 0,Correlation threshold,Training data R^2 score,Test data R^2 score,Training RMSE,Test RMSE,Number of features,Depth number,Number of estimators,Number of neighbors
DT,280.0,0.48,0.617326,0.421940,26.876269,29.743411,2.0,2.0,NaN,NaN
RF,140.0,0.45,0.782527,0.366957,20.260808,31.125827,6.0,NaN,9.0,NaN
KNN,72.0,0.48,0.581854,0.400065,28.094305,30.300975,2.0,NaN,NaN,5.0

In [4]:
import pandas as pd

# Define the path to the Excel file
file_path = '../Data/Quality_ee_42_.xlsx'

# Define the sheets and metrics
sheets = ["MLR", "DT", "RF", "KNN", "SVM"]
metrics = ['Training data R^2 score', 'Test data R^2 score', 'Training RMSE', 'Test RMSE']
number_of_features = 10
# Initialize a dictionary to store the best models
best_models = {}

# Iterate through each sheet to find the best model
for sheet in sheets:
    # Read the data from the current sheet
    df = pd.read_excel(file_path, sheet_name=sheet)
    df_filtered = df[df['Number of features'] < number_of_features]
    # Filter the DataFrame based on the criteria
    # The model must have higher training parameters than test parameters
    filtered_df = df_filtered[(df_filtered['Training data R^2 score'] > df_filtered['Test data R^2 score']) & 
                     (df_filtered['Training RMSE'] < df_filtered['Test RMSE']) & 
                              (df_filtered['Test data R^2 score'] > 0.36)]
    
    if not filtered_df.empty:
        # Find the row with the maximum Test Accuracy
        best_model = filtered_df.loc[filtered_df['Test data R^2 score'].idxmax()]
        best_model = filtered_df.loc[filtered_df['Correlation threshold'].idxmax()]
        best_models[sheet] = best_model

# Convert the results to a DataFrame for better visualization
best_models_df = pd.DataFrame.from_dict(best_models, orient='index')

# Print the best models for each method
print("Best Models for Each Method:")
best_models_df

Best Models for Each Method:

,Unnamed: 0,Correlation threshold,Training data R^2 score,Test data R^2 score,Training RMSE,Test RMSE,Number of features,Depth number,Number of estimators,Number of neighbors
DT,283.0,0.48,0.646611,0.513917,25.636812,28.778964,2.0,5.0,NaN,NaN
RF,190.0,0.48,0.623329,0.560402,26.467863,27.368300,2.0,NaN,2.0,NaN
KNN,65.0,0.47,0.450881,0.377418,31.957360,32.570036,4.0,NaN,NaN,5.0

In [5]:
import numpy as np
np.sqrt(0.621787)

0.7885347170543603

In [6]:
np.sqrt(0.864952)

0.9300279565690486

In [7]:
try:
    import numpy as np
    print("The correlation coefficient for test data equals: "+str(np.sqrt(best_models_df['Test data R^2 score']['RF'])))
    print("The correlation coefficient for training data equals: "+str(np.sqrt(best_models_df['Training data R^2 score']['RF'])))
except:
    print("Error gathering the data...")

The correlation coefficient for test data equals: 0.7486001445390318
The correlation coefficient for training data equals: 0.7895117506735441

In [8]:
import pandas as pd

# Define the path to the Excel file
file_path = '../Data/Quality_ee_15_.xlsx'

# Define the sheets and metrics
sheets = ["MLR", "DT", "RF", "KNN", "SVM"]
metrics = ['Training data R^2 score', 'Test data R^2 score', 'Training RMSE', 'Test RMSE']
number_of_features = 10
# Initialize a dictionary to store the best models
best_models = {}

# Iterate through each sheet to find the best model
for sheet in sheets:
    # Read the data from the current sheet
    df = pd.read_excel(file_path, sheet_name=sheet)
    df_filtered = df[df['Number of features'] < number_of_features]
    # Filter the DataFrame based on the criteria
    # The model must have higher training parameters than test parameters
    filtered_df = df_filtered[(df_filtered['Test data R^2 score'] > 0.36)]
    
    if not filtered_df.empty:
        # Find the row with the maximum Test Accuracy
        best_model = filtered_df.loc[filtered_df['Test data R^2 score'].idxmax()]
        best_model = filtered_df.loc[filtered_df['Correlation threshold'].idxmax()]
        best_models[sheet] = best_model

# Convert the results to a DataFrame for better visualization
best_models_df = pd.DataFrame.from_dict(best_models, orient='index')

# Print the best models for each method
print("Best Models for Each Method:")
best_models_df

Best Models for Each Method:

Empty DataFrame
Columns: []
Index: []

In [9]:
import pandas as pd

# Define the path to the Excel file
file_path = '../Data/Quality_ee_28_.xlsx'

# Define the sheets and metrics
sheets = ["MLR", "DT", "RF", "KNN", "SVM"]
metrics = ['Training data R^2 score', 'Test data R^2 score', 'Training RMSE', 'Test RMSE']
number_of_features = 10
# Initialize a dictionary to store the best models
best_models = {}

# Iterate through each sheet to find the best model
for sheet in sheets:
    # Read the data from the current sheet
    df = pd.read_excel(file_path, sheet_name=sheet)
    df_filtered = df[df['Number of features'] < number_of_features]
    # Filter the DataFrame based on the criteria
    # The model must have higher training parameters than test parameters
    filtered_df = df_filtered[(df_filtered['Test data R^2 score'] > 0.36)]
    
    if not filtered_df.empty:
        # Find the row with the maximum Test Accuracy
        best_model = filtered_df.loc[filtered_df['Test data R^2 score'].idxmax()]
        best_model = filtered_df.loc[filtered_df['Correlation threshold'].idxmax()]
        best_models[sheet] = best_model

# Convert the results to a DataFrame for better visualization
best_models_df = pd.DataFrame.from_dict(best_models, orient='index')

# Print the best models for each method
print("Best Models for Each Method:")
best_models_df

Best Models for Each Method:

,Unnamed: 0,Correlation threshold,Training data R^2 score,Test data R^2 score,Training RMSE,Test RMSE,Number of features,Depth number,Number of estimators,Number of neighbors
DT,280.0,0.48,0.617326,0.421940,26.876269,29.743411,2.0,2.0,NaN,NaN
RF,140.0,0.45,0.782527,0.366957,20.260808,31.125827,6.0,NaN,9.0,NaN
KNN,72.0,0.48,0.581854,0.400065,28.094305,30.300975,2.0,NaN,NaN,5.0

In [10]:
import pandas as pd

# Define the path to the Excel file
file_path = '../Data/Quality_ee_42_.xlsx'

# Define the sheets and metrics
sheets = ["MLR", "DT", "RF", "KNN", "SVM"]
metrics = ['Training data R^2 score', 'Test data R^2 score', 'Training RMSE', 'Test RMSE']
number_of_features = 10
# Initialize a dictionary to store the best models
best_models = {}

# Iterate through each sheet to find the best model
for sheet in sheets:
    # Read the data from the current sheet
    df = pd.read_excel(file_path, sheet_name=sheet)
    df_filtered = df[df['Number of features'] < number_of_features]
    # Filter the DataFrame based on the criteria
    # The model must have higher training parameters than test parameters
    filtered_df = df_filtered[(df_filtered['Test data R^2 score'] > 0.36)]
    
    if not filtered_df.empty:
        # Find the row with the maximum Test Accuracy
        best_model = filtered_df.loc[filtered_df['Test data R^2 score'].idxmax()]
        best_model = filtered_df.loc[filtered_df['Correlation threshold'].idxmax()]
        best_models[sheet] = best_model

# Convert the results to a DataFrame for better visualization
best_models_df = pd.DataFrame.from_dict(best_models, orient='index')

# Print the best models for each method
print("Best Models for Each Method:")
best_models_df

Best Models for Each Method:

,Unnamed: 0,Correlation threshold,Training data R^2 score,Test data R^2 score,Training RMSE,Test RMSE,Number of features,Depth number,Number of estimators,Number of neighbors,C,Gamma,Kernel
DT,336.0,0.50,0.320864,0.373178,35.539899,32.680758,1.0,2.0,NaN,NaN,NaN,NaN,NaN
RF,190.0,0.48,0.623329,0.560402,26.467863,27.368300,2.0,NaN,2.0,NaN,NaN,NaN,NaN
KNN,70.0,0.48,0.520097,0.558335,29.875436,27.432562,2.0,NaN,NaN,3.0,NaN,NaN,NaN
SVM,460.0,0.50,0.175427,0.444055,39.160869,30.777675,1.0,NaN,NaN,NaN,10.0,0.1,rbf